language: node_js
node_js:
- '8'
- '10'
- '12'
- stable
- lts
- lts/*
os:
- linux
- osx
- windows

after_success: npm run coverage
jobs:
  include:
  - stage: npm publish
    node_js: lts/*
    os: linux
    script: echo deploy to npm
    deploy:
      provider: npm
      email: sogo@longtail-software.co.jp
      api_token:
        secure: IbiQCd5yXbdXpPumHXD5VFuy3ydQj6RXmtr8wYEjNcuy3EDmy26KDGuEAvJ5YAqT7l7A/GaeSYiyAFeJ6lYbAPc6oKkOc5OM9mTg9wFL0oXauQD2iBg1QoEO+Bqace/0UYWMgs80ujP5wEwO+kFLOYyVaeGXXptTFu1NEfnzGtfn01ef1T2BAJZ/La4Ww8F+q2auBx3Erx2kFGemOCKg0qfOZBh3iq+XMeibM/WZNeKS+Ji8CB26apIJr4LOgLZc6pZgcqYLuKVAErBn/YTiHL+HA2w+Sn3vIM9AUHujHM9xnMFmJDa8ylgXv6litG+hTEqZjFGnkzk9tqleUsSKXc53jVTVk6JQPuyDrLeBAKDWHWwqJTI6vlcTrhppgrK2aSOMJnmc6r92iyJbFKBLVhZ4vDaBR70iJQySJiRqVKwAdxLvu937QqRBMXGQmxqkXGQ6KGTkrmkcp9rHoVDQ7Rdd2jpoEBmlL7yp6EkBEWoZWB0+krYGxOrtROP0nfSUbKxgfPDQmBSooQRelWeZHMFl6WWovnhBbvp6y5S3S1HfJuNenRhZSWCyv1VLL8AnDGaIQQEbDCUMFnU/KswqBHCA15ks94BK+ULN8z1YlDMA4zDZj5OqLYMX/cqYXapVjMrWicZNh/HPeqNoTKe3R9ZOIbYattOW8uCxTJY71yY=
      on:
        tags: true
  exclude:
  - os: windows
    node_js: lts/*
  - os: linux
    node_js: lts
  - os: osx
    node_js: lts
      
notifications:
  email: false
  slack:
    secure: Bf4kS2/129KYnemC45ETqbOgVJhXwLJpe4WGaC6Gz03JBAs2XtGwp4OhOpAZmTL+rMxwKXiQViE8ymDGS3l5GXc9rq7Uaxq8LvPCoSp8Ec8FLLRWBJm1z2MjTfUf5L2HOyoeajyczUvCuLbVHrR3sos2vNASzh3fy1ATmclIAcLDcIfrpnRubx0fBkFGvbJZLIMg9bel0L+meQD4UeSe5UYvjliiTDiGWCGYRYUI3pqb5Bx3ju66VYTV4FQwZIS1cB12BHhdRv1KranJ8mvIqK1zQUovhNQyc/2nUyA7/LeagiE/FhFuPButNHyietDW3dSrVenlpH2U5jE5Pss6sh6pkWhDOsCGKx6G+2dgRBAHe8KiOMyLKGO92UnAqp3vd4RfVzevatUJVnUJTeRW7SKs9PiXKXtvbrUDnL2tjpbOosgXouHvYHeqqwvaRibTFuV+CMU7dUn+0Z5SCv0/vDqkV4OWkpYM6Ms0IomaLfZ5T8mDFonts+fj+/U3F1xf5T/6lxiO5yYvgPASWKB40RxYccbeRwmbg3rwqyGB5s545qezxXENILzZlPgZtRTQZ7poCem0EofFr2XYnaCfBXsUQwj9cZF3bcgXW8ZijrBv5YpopL4Fej7IIiWtD6gNLX5ep25NRvqAxW3s1lShS5980WprKGchElwovOGgdJs=
