name: run UT
on:
  push:
    tags-ignore:
      - 'v*'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test
      - run: npm run coverage
      - uses: actions/upload-artifact@v4
        if: matrix.node-version == '22.x'
        with:
          name: code-coverage-report
          path: coverage-report.lcov
          retention-days: 1
