name: run UT
on:
  push:
    tags-ignore:
      - 'v*'
    branches:
      - '*'
  pull_request:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test
      - run: npm run coverage
      - uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage-report.lcov
          retention-days: 1
  coverage:
    needs: [test]
    name: coverage report
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.cc_test_reporter_id }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
      - uses: paambaati/codeclimate-action@v5.0.0
        with:
          coverageLocations: "coverage-report.lcov:lcov"
